# Package definitions exports

export_file(
    name = "package_defs.bzl",
    visibility = ["PUBLIC"],
)

export_file(
    name = "versions.bzl",
    visibility = ["PUBLIC"],
)

export_file(
    name = "registry.bzl",
    visibility = ["PUBLIC"],
)
