# Package definitions exports

export_file(
    name = "package_defs.bzl",
    visibility = ["PUBLIC"],
)

# Platform targeting helpers
export_file(
    name = "platform_defs.bzl",
      visibility = ["PUBLIC"],
)

export_file(
    name = "versions.bzl",
    visibility = ["PUBLIC"],
)

export_file(
    name = "registry.bzl",
    visibility = ["PUBLIC"],
)
