load("//defs:package_defs.bzl", "rootfs")

rootfs(
    name = "installer-rootfs",
    packages = [
        "//packages/linux/system/apps:coreutils",
        "//packages/linux/core/util-linux:util-linux",
        "//packages/linux/core/procps-ng:procps-ng",
        "//packages/linux/system/apps/shadow:shadow",
        "//packages/linux/system/security/auth/pam:pam",
        "//packages/linux/core/file:file",
        "//packages/linux/core/bash:bash",
        "//packages/linux/core/zlib:zlib",
        "//packages/linux/core/glibc:glibc",
        "//packages/linux/boot/grub:grub",
        "//packages/linux/boot/efibootmgr:efibootmgr",
        "//packages/linux/system/init:systemd",
        "//packages/linux/network:openssl",
        "//packages/linux/network:curl",
        "//packages/linux/network:iproute2",
        "//packages/linux/network:openssh",
        "//packages/linux/editors:vim",
    ],
    visibility = ["PUBLIC"],
)
